### ISSUE TITLE
(Honor 6X) Compatibility issue with Android 7.0

### ISSUE THREAD

**Issue by rib4n** [pkern/kitcard-reader#27]
(Honor 6X) Compatibility issue with Android 7.0
[Google Play Store error]

Google Play Store says: "Your device is not compatible with this version."

**Comment by SolidTux** [comment]
Same for me with the Moto X4.

**Comment by pkern** [comment]
The default assumption that I have is this: Whenever this is shown Play Store is usually correct in that the device does not have the NXP chip required to communicate with the card (Mifare Classic). There might be corner cases where this is not the case, but then they should be reported as such.
